CREATE TABLE CUSTOMERS ( 
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  first_name varchar(45) NOT NULL,
  last_name varchar(45) NOT NULL,
  address_1 varchar(100) NOT NULL,
  address_2 varchar(45) NOT NULL,
  city varchar(20) NOT NULL,
  state varchar(10) NOT NULL,
  zip_code varchar(9) NOT NULL,
  country varchar(10) NOT NULL,
  email varchar(45) NOT NULL,
  user_name varchar(45) NOT NULL,
  password varchar(45) NOT NULL,
  reg_date date NOT NULL);